[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pt_lex"
version = "0.1.0"
authors = [
  { name="Original: msamribeiro, Packager: lbartolessi", email="lbartolessi@zoho.eu" },
]
description = "A Python library for Portuguese lexical analysis, adapted for installation."
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "requests",
    "beautifulsoup4",
]

[project.urls]
"Homepage" = "https://github.com/lbartolessi/pt-lex-installable"
"Bug Tracker" = "https://github.com/lbartolessi/pt-lex-installable/issues"
